.TH jxlib 3
.SH NAME
jx_catch, jx_debug, jx_free, jx_simple, jx_simple_from_token, jx_string, jx_number, jx_symbol, jx_int, jx_float, jx_key, jx_object, jx_array, jx_append, jx_copy, jx_select, jx_equal, jx_compare, jx_sort, jx_token, jx_parse_begin, jx_parse_divert, jx_parse_newbuf, jx_parse_token, jx_parse_complete, jx_parse_end, jx_parse_string, jx_parse_file, jx_serialize, jx_print,  jx_by_key, jx_by_deep_key, jx_by_index, jx_by_expr, jx_default_text, jx_text, jx_length, jx_is_null, jx_compare, jx_text_by_key, jx_text_by_index, jx_text_by_expr \- A library for accessing JSON data
.SH SYNTAX
\fB#include <jx.h>\fR
.br
\fBvoid\fR jx_catch(\fBvoid\fR (*\fIf\fR)(\fBjx_parse_t\fR *\fIparse\fR, \fBchar\fR *\fIfmt\fR, ...));
.br
\fBchar\fR *jx_debug(\fBchar\fR *\fIflags\fR);
.br
\fBvoid\fR jx_free(\fBjx_t\fR *\fIjson\fR);
.br
\fBjx_t\fR *jx_simple(\fBchar\fR *\fIstr\fR, \fBsize_t\fR \fIlen\fR, \fBjx_type_t\fR \fItype\fR);
.br
\fBjx_t\fR *jx_simple_from_token(\fBjx_token_t\fR *\fItoken\fR);
.br
\fBjx_t\fR *jx_string(\fBchar\fR *\fIstr\fR, \fBsize_t\fR \fIlen\fR);
.br
\fBjx_t\fR *jx_number(\fBchar\fR *\fIstr\fR, \fBsize_t\fR \fIlen\fR);
.br
\fBjx_t\fR *jx_symbol(\fBchar\fR *\fIstr\fR, \fBsize_t\fR \fIlen\fR);
.br
\fBjx_t\fR *jx_int(\fBint\fR \fIi\fR);
.br
\fBjx_t\fR *jx_float(\fBdouble\fR \fIf\fR);
.br
\fBjx_t\fR *jx_key(\fBchar\fR *\fIkey\fR, \fBjx_t\fR *\fIvalue\fR);
.br
\fBjx_t\fR *jx_object();
.br
\fBjx_t\fR *jx_array();
.br
\fBint\fR jx_append(\fBjx_t\fR *\fIcontainer\fR, \fBjx_t\fR *\fImore\fR);
.br
\fBjx_t\fR jx_copy(\fBjx_t\fR *\fIjson\fR);
.br
\fBjx_t\fR jx_select(\fBjx_t\fR *\fIobj\fR, \fBjx_t\fR *\fIcolumns\fR, \fBjx_t\fR *\fIas\fR);
.br
\fBint\fR jx_fixemptyobject;
.br
\fBchar\fR *jx_token(\fBchar\fR *\fIstr\fR, \fBjx_token_t\fR *\fItoken\fR);
.br
\fBvoid\fR jx_parse_begin(\fBjx_parse_t\fR *\fIstate\fR, \fBint\fR \fImaxnest\fR);
.br
\fBjx_parse_divert_t\fR *jx_parse_divert(\fBjx_parse_t\fR *\fIstate\fR, \fBchar\fR *\fIexpr\fR,
.br
\ \ \ \fBjx_t\fR *(*\fIf\fR)(\fBjx_parse_t\fR *\fIparse\fR, \fBjx_t\fR *\fIelement\fR));
.br
\fBvoid\fR jx_parse_newbuf(\fBjx_parse_t\fR *\fIstate\fR, \fBchar\fR *\fIbuf\fR, \fBlong\fR \fIoffset\fR);
.br
\fBvoid\fR jx_parse_token(\fBjx_parse_t\fR *\fIstate\fR, \fBjx_token_t\fR *\fItoken\fR);
.br
int jx_parse_complete(\fBjx_parse_t\fR *\fIstate\fR);
.br
\fBjx_t\fR *jx_parse_end(\fBjx_parse_t\fR *\fIstate\fR);
.br
\fBjx_t\fR *jx_parse_string(\fBchar\fR *\fIstr\fR);
.br
\fBjx_t\fR *jx_parse_file(\fBjx_parse_t\fR *\fIstate\fR, \fBchar\fR *\fIfilename\fR);
.br
\fBchar\fR *jx_serialize(\fBjx_t\fR *\fIjson\fR);
.br
\fBvoid\fR jx_print(\fBjx_t\fR *\fIjson\fR, \fBFILE\fR *\fIfp\fR, \fBint\fR \fIindent\fR);
.br
\fBint\fR jx_same(\fBjx_t\fR *\fIleft\fR, \fBjx_t\fR *\fIright\fR);
.br
\fBint\fR jx_ignorecase;
.br
\fBjx_t\fR *jx_by_key(\fBjx_t\fR *\fIcontainer\fR, \fBchar\fR *\fIkey\fR);
.br
\fBjx_t\fR *jx_by_deep_key(\fBjx_t\fR *\fIcontainer\fR, \fBchar\fR *\fIkey\fR);
.br
\fBjx_t\fR *jx_by_index(\fBjx_t\fR *\fIcontainer\fR, \fBint\fR \fIidx\fR);
.br
\fBjx_t\fR *jx_by_expr(\fBjx_t\fR *\fIcontainer\fR, \fBchar\fR *\fIexpr\fR, \fBchar\fR **\fInext\fR);
.br
\fBchar\fR *jx_default_text(\fBchar\fR *\fInewdefault\fR);
.br
\fBchar\fR *jx_text(\fBjx_t\fR *\fIjson\fR);
.br
\fBint\fR *jx_length(\fBjx_t\fR *\fIcontainer\fR);
.br
\fBchar\fR *jx_text_by_key(\fBjx_t\fR *\fIcontainer\fR, \fBchar\fR *\fIkey\fR);
.br
\fBchar\fR *jx_text_by_index(\fBjx_t\fR *\fIcontainer\fR, \fBchar\fR *\fIindex\fR);
.br
\fBchar\fR *jx_text_by_expr(\fBjx_t\fR *\fIcontainer\fR, \fBchar\fR *\fIexpr\fR, \fBchar\fR **\fInext\fR);

.SH DESCRIPTION
The \fBjx\fR library contains functions for reading, manipulating, and writing
JSON data.
.P
JSON is a way to represent complex data structures in text.
It is, essentially, a subset of the JavaScript language that is limited
to literals.
JavaScript is more comfortable with with JSON than with XML,
and JSON data is much more compact than XML,
and it requires fewer overlapping standards than XML (SOAP/WSDL/XSchema/DTD/...).
.P
This library can parse a JSON string to generate a C/C++ data tree,
extract data from the tree, create or manipulate a tree, and output it
as JSON again.
.P
Don't be put off by the number of functions;
they're there for the sake of versatility and convenience.
Simple JSON manipulation is simple \-
simple enough that this manual page contains the complete source code
for 9 programs using the library.
.P
Often, JSON data contains an array of objects.
These arrays can be very large \- potentially larger than you want to
suck into memory before you even begin processing the data.
This library has an efficient way out of that: You can tell the library
to divert elements of a given array to a function that you supply.
This gives you a way to process each element one at a time, as the
data is being parsed.
See the \fBjx_parse_divert\fR() function below.

.SH "DATA TYPES"

.SS "jx_t"
.nf
\fBtypedef struct\fR {
    \fBjx_t\fR *\fInext;\fR
    \fBjx_t\fR *\fIfirst;\fR
    \fBjx_type_t\fR \fItype;\fR
    \fBchar\fR \fItext\fR[];
} \fBjx_t\fR;
.fi
.P
The \fBjx_t\fR data type is used to store the JSON data.
Most of the functions in this library either return a pointer to a
\fIjx_t\fR or take a pointer to one as a parameter.
.P
The \fItype\fR identfies the type of data stored in this \fBjx_t\fR,
as is described in the following subsection.
The \fItext\fR text field contains the text form of the data, if the
type is one of \fBJX_KEY\fR, \fBJX_STRING\fR, \fBJX_NUMBER\fR, or
\fBJX_SYMBOL\fR.
The \fIfirst\fR field points to the
first array element if \fItype\fR is \fBJX_ARRAY\fR,
first object member if \fItype\fR is \fBJX_OBJECT\fR,
or the value associated with a key if \fItype\fR is \fBJX_KEY\fR.
The \fInext\fR field points to each successive element/member.
.P
To iterate over the elements of an array, use the array's \fBjx_t\fR's
\fIfirst\fR field to find the first element, and each element's \fInext\fR
field to find each successive element.
The same technique also works for iterating over the members of an object;
each member will be a \fBJX_KEY\fR with the member name in the \fItext\fR
field and the value referenced by the \fIfirst\fR field.
.nf
    #include <stdio.h>
    #include <jx.h>
    int main(int argc, char **argv)
    {
        jx_t *array, *elem;
        array = jx_parse_string("[1,2,4,8,16,32]");
        for (elem = array->first; elem; elem = elem->next) {
            puts(jx_text(elem));
        }
        jx_free(array);
    }
.fi
.P
Here's a tricky one.
In data that is converted from XML to JSON, an XML repeated tag may be
represented sometimes as a single object, and sometimes as an array of objects.
It really depends on your XML-to-JSON converter.
If this happens in your world, then your JSON code needs to be adaptable.
My method: first check the type, and if it's an array
then skip to the first member of the array.
Otherwise just process the item directly, as though it was an array element;
this is safe because in this context the "next" field is guaranteed to be NULL
so it'll look like the only item in an array's linked list.
.nf
    #include <stdio.h>
    #include <jx.h>
    int main(int argc, char **argv)
    {
        jx_t *fromXML, *item;
        fromXML = jx_parse_file(NULL, "fromXML.json");
	item = jx_by_key(fromXML, "PossiblyRepeatedElement");
        if (item) {
            if (item->type == JX_ARRAY)
                item = item->first;
            for (; item; item = item->next)
                puts(jx_text(item));
        }
        jx_free(fromXML);
    }

.SS "jx_type_t"
.nf
\fBtypedef\fR \fBenum\fR {
    \fBJX_BADTOKEN\fR, \fBJX_NEWLINE\fR,
    \fBJX_OBJECT\fR, \fBJX_ENDOBJECT\fR,
    \fBJX_ARRAY\fR, \fBJX_ENDARRAY\fR,
    \fBJX_KEY\fR, \fBJX_STRING\fR, \fBJX_NUMBER\fR, \fBJX_SYMBOL\fR
} \fBjx_type_t\fR;
.fi
.P
This represents the types of tokens that may be parsed.
.P
The \fBJX_OBJECT\fR, \fBJX_ARRAY\fR, \fBJX_KEY\fR, \fBJX_STRING\fR,
\fBJX_NUMBER\fR, and \fBJX_SYMBOL\fR values are also used in the
\fBjx_t\fR \fItype\fR field to identify the type of data stored there.
The other values are used internally by the parser, and will not appear in any
parsed \fBjx_t\fR data.


.SS "jx_parse_t"
This is an opaque data type, used to store the parsing context.
You don't always need a parsing context, but if you want to add a
diversion then you'll want to create one so you can attach the diverter
to it before you start parsing.

.SS "jx_divert_t"
.nf
\fBtypedef struct\fR jx_divert_s {
	\fBstruct\fR jx_divert_s *next;
	jx_t *(*handler)(jx_parse_t *parse, jx_t *element);
	jx_t	*found;
	\fBvoid\fR	*data;
	\fBlong\fR	diverted;
	\fBlong\fR	deleted;
	\fBlong\fR	changed;
	\fBchar\fR	expr[1];
} jx_divert_t;
.fi
.P
This is mostly an internal data type, used to store the list of
diversions for a given
.B jx_parse_t
parse state.
The only members you're likely to access directly are
.RI \" data \"
which can store a pointer to data supplied by your application,
and
.RI \" diverted \",
.RI \" deleted \",
or
.RI \" changed \"
which are counters for how many parsed members were diverted (parsed),
how many of those were deleted (because the handler returned NULL),
and how many were changed (because the handler returned a different
.B jx_t
pointer).

.SH "ERROR HANDLING"
The following functions are useful when debugging programs or their data.

.IP "\fBvoid\fR jx_catch(\fBvoid\fR (*\fIf\fR)(\fBjx_parse_t\fR *\fIparse\fR, \fBchar\fR *\fIfmt\fR, ...));"
During parsing or manipulation, if a function in the jx library detects an
error then it normally outputs an error message and exits.
This function gives you a way to install your own error handler.
Passing NULL reverts to the default one.
.IP
jx_catch() takes a single parameter, which is a pointer to a function that
will handle errors.
.IP
That handler function takes at least 2  parameters:
The jx_parse_t indicating the parse state (or NULL if nor parsing)
including the filename and line number if available, and 
a printf-style formatting string possibly followed by other parameters as
indicated by the formatting string.
The formatting string does \fInot\fR include the filename and line number;
if you want to output those, you'll need to explicitly do so before outputting
the formatted error message.
If the handler function returns (doesn't exit) then processing will continue.

.IP "\fBvoid\fR jx_throw(\fBjx_parse_t\fI state\fR, \fBchar *\fRfmt\fR, ...);"
This invokes the error catcher that you set via \fBjx_catch()\fR.
The \fIstate\fR parameter is a parse state, or NULL for errors that occur
outside of parsing such as trying to insert an element into a non-array.
The \fIfmt\fR parameter is a printf()-style formatting string, generally
without a \\n at the end.
Depending on \fIfmt\fR, there may be other parameters.
.IP
See the source code's \fBjx_throw_default()\fR function for an example.
.IP
NOTE: jx_throw() is really just a variable that stores the function pointer
you passed via jx_catch().

.IP "\fBchar\fR *jx_debug(\fBchar\fR *\fIflags\fR);"
This gives you a way to specify that some debugging output should be written
to stderr.
The \fIflags\fR parameter is a string containing
"+" to add any following debugging letters,
"-" to remove any following debugging letters,
"=" to use only the following debugging letters,
or a letter to control a particular type of debugging output.
The letters are
"b" to show the input buffer contents while reading from a file,
"f" for file input reads or buffer shifts while reading from a file, or
"t" to output tokens as they're parsed.
Initially, no debugging output is shown.
If the string doesn't start with "+", "-", or "=" then "+" is assumed.
If the function succeeds, then it returns NULL.
Otherwise it returns a pointer to the bad character in \fIflags\fR.

.SH MANIPULATING
The following functions are used to create or alter \fBjx_t\fR trees.
The data they add to the tree does not necessarily come from a JSON source;
you can use these to create a \fBjx_t\fR tree from any data within your
program, and then use \fBjx_serialize()\fR or \fBjx_print()\fR to
convert it to JSON text.

.IP "\fBvoid\fR jx_free(\fBjx_t\fR *\fIjx\fR);"
This frees a \fBjx_t\fR tree that was created via the other manipulation
functions.

.IP "\fBjx_t\fR *jx_simple(\fBchar\fR *\fIstr\fR, size_t \fIlen\fR, \fBjx_type_t\fR \fItype\fR);"
.IP "\fBjx_t\fR *jx_simple_from_token(\fBjx_token_t\fR *\fItoken\fR);"
.IP "\fBjx_t\fR *jx_string(\fBchar\fR *\fIstr\fR, size_t \fIlen\fR);"
.IP "\fBjx_t\fR *jx_number(\fBchar\fR *\fIstr\fR, size_t \fIlen\fR);"
.IP "\fBjx_t\fR *jx_symbol(\fBchar\fR *\fIstr\fR, size_t \fIlen\fR);"
.IP "\fBjx_t\fR *jx_int(int \fIi\fR);"
.IP "\fBjx_t\fR *jx_float(double \fIf\fR);"
.IP "\fBjx_t\fR *jx_key(\fBchar\fR *\fIkey\fR, \fBjx_t\fR *\fIvalue\fR);"
.IP "\fBjx_t\fR *jx_object();"
.IP "\fBjx_t\fR *jx_array();"
These all create a single \fBjx_t\fR node.
.IP
\fBjx_simple\fR(\fIstr\fR, \fIlen\fR, \fItype\fR) is the lowest-level
function which merely allocates a node with given text and type;
the other \fBjx_t\fR fields will be initialized as NULL pointers.
You can pass NULL for the \fIstr\fR, in which case no text is stored.
Otherwise, \fIlen\fR must indicate the length of \fIstr\fR.
.IP
All of the other functions in the above list are merely wrappers around
that function.

.IP "\fBvoid\fR jx_append(\fBjx_t\fR *\fIcontainer\fR, \fBjx_t\fR *\fImore\fR);"
This combines two \fBjx_t\fR trees.
The \fIcontainer\fR must be a \fBJX_ARRAY\fR, \fBJX_OBJECT\fR, or \fBJX_KEY\fR.
.IP
For \fBJX_KEY\fR containers, this assigns a value to the key.
If the key already had a value, the new value replaces it and the old
value is freed.
.IP
For \fBJX_OBJECT\fR containers, the \fImore\fR parameter should be a
\fBJX_KEY\fR with the new member's name and value.
If the container already contains a member with the same name, the new
member will replace the old one, and the old one will be freed.
This also applies if the container is a \fBJX_ARRAY\fR and the \fImore\fR
parameter is a \fBJX_KEY\fR.
For example, the following code snippet would add or replace a member with the
name "x" to \fIobj\fR, and give it the value 6:
.nf

    jx_append(obj, jx_key("x", jx_int(6)) );
.IP
For \fBJX_ARRAY\fR containers where \fImore\fR is not a \fBJX_KEY\fR,
the new value is simply appended to the array's list of elements.
.IP "\fBjx_t\fR jx_copy(\fBjx_t\fR *\fIjson\fR);"
Create a "deep" copy of JSON data.
If
.I json
is an array, object, or key then each member within it is also copied.
The end result is another
.B jx_t
data object which is identical to
.I json
but independent of it;
you can alter or free one without affecting the other.
.IP "\fBjx_t\fR jx_select(\fBjx_t\fR *\fIobj\fR, \fBjx_t\fR *\fIcolumns\fR, \fBjx_t\fR *\fIas\fR);"
Create a new JSON object containing selected members of the 
.I obj
object.
The
.I columns
parameter is an array of member names
or JavaScript-like expressions (as strings)
for finding the members.
The
.I as
parameter, if not NULL, is a parallel array of names to use for the fields
in the resulting object.
The original object is unchanged.
.IP
The following example will print {"width":10,"height":12}
.nf

    #include <stdio.h>
    #include <jx.h>
    int main()
    {
    	jx_t *xyz, *columns, *as, *result;

        xyz = jx_parse_string("{\e"x\e":10,\e"y\e":12,\e"z\e":22}");
        columns = jx_parse_string("[\e"x\e",\e"y\e"]");
        as = jx_parse_string("[\e"width\e",\e"height\e"]");

        result = jx_select(xyz, columns, as);
        jx_print(result, stdout, 0);

        jx_free(xyz);
        jx_free(columns);
        jx_free(as);
        jx_free(result):

        return 0;
    }
.IP "\fBvoid\fR jx_sort(\fBjx_t\fR *\fIarray\fR, \fBjx_t\fR *\fIorderby\fR);"
Sort an array of objects in-place (meaning the same
.I array
that you pass in gets rearranged, instead of creating a whole new array).
The
.I orderby
list is an array of member names/expressions to compare, where each one may
be preceded by the symbol
.B true
to make it be sorted in descending order.
See the jx_compare() function for more information.

.SH PARSING
The following functions convert JSON text to a \fBjx_t\fR tree.

.IP "\fBjx_t\fR *jx_parse_string(\fBchar\fR *\fIstr\fR);"
Parse a string containing JSON text, and return a corresponding
\fBjx_t\fR tree.
The following example parses a literal string, and then pretty-prints it.
.nf

    #include <stdio.h>
    #include <jx.h>
    int main(int argc, char **argv)
    {
        jx_t *xy;

        xy = jx_parse_string("{\e"x\e":10,\e"y\e":12}");
        jx_print(xy, stdout, 0);
        jx_free(xy);
        return 0;
    }
.fi
.IP "\fBjx_t\fR *jx_parse_file(\fBjx_parse_t\fR *\fIstate\fR, \fBchar\fR *\fIfilename\fR);"
Parse the contents of a file as JSON text, and return the corresponding
\fBjx_t\fR tree.
.IP
The \fIstate\fR parameter may be NULL, in which case \fBjx_parse_file\fR()
will use a temporary parse state.
The most common reasons for passing your own parse state (and calling the
\fBjx_parse_begin\fR() and \fBjx_parse_end()\fR functions to manage it)
are to handle JSON data that's split across multiple files, or
to use \fBjx_parse_divert\fR() for handling array elements individually
as they're parsed, instead of building the whole \fBjx_t\fR tree in
memory and then scanning the tree.
.IP
The following example pretty-prints any JSON files named on the command line.
.nf
    #include <stdio.h>
    #include <jx.h>
    int main(int argc, char *argv)
    {
        int    i;
        jx_t *j;

        for (i = 1; i < argc, i++) {
            j = jx_parse_file(NULL, argv[i]);
            if (j) {
                jx_print(j, stdout, 0);
                jx_free(j);
            }
        }
        return 0;
    }
.fi

.IP "\fBvoid\fR jx_parse_begin(\fBjx_parse_t\fR *\fIstate\fR, \fBint\fR \fImaxnest\fR);"
.IP "\fBjx_t\fR *jx_parse_end(\fBjx_parse_t\fR *\fIstate\fR);"
These functions initialize and terminate a parse state.
The state itself will typically be stored in a local variable within your
function.
.IP
The following example concatenates JSON fragments in all files named on the
command line, and then pretty-prints the combined data.
.nf
    #include <stdio.h>
    #include <jx.h>
    int main(int argc, char *argv)
    {
        int    i;
        jx_t *j;
        jx_parse_t state;

        jx_parse_begin(&state, 30);
        for (i = 1; i < argc, i++)
            (void)jx_parse_file(&state, argv[i]);
        j = jx_parse_end(&state);
        if (j) {
            jx_print(j, stdout, 0);
            jx_free(j);
        }
        return 0;
    }
.fi

.IP "int jx_parse_complete(\fBjx_parse_t\fR *\fIstate\fR);"
This returns a flag indicating whether the current parse state represents
a complete object; i.e., whether the final "}" has been read.
The following example uses
.BR jx_parse_complete ()
to pretty-print JSON data from files, whether
the files are each complete by themselves, or fragments that need to be
combined.
.nf
    #include <stdio.h>
    #include <jx.h>
    int main(int argc, char *argv)
    {
        int    i;
        jx_t *j;
        jx_parse_t state;

        jx_parse_begin(&state, 30);
        for (i = 1; i < argc, i++) {
            (void)jx_parse_file(&state, argv[i]);
            if (jx_parse_complete(&state)) {
                j = jx_parse_end(&state);
                if (j) {
                    jx_print(j, stdout, 0);
                    jx_free(j);
                }
                jx_parse_begin(&state, 30);
            }
        }
        j = jx_parse_end(&state);
        jx_free(j);
        return 0;
    }
.fi

.IP "\fBjx_parse_divert_t\fR *jx_parse_divert(\fBjx_parse_t\fR *\fIstate\fR, \fBchar\fR *\fIexpr\fR,"
.IP "\ \ \ \fBjx_t\fR *(*\fIf\fR)(\fBjx_parse_t\fR *\fIparse\fR, \fBjx_t\fR *\fIelement\fR));"
JSON data often contains an array of many objects -- possibly millions.
Parsing all of them and building an in-memory parse tree is not always the
best way to process that data.
The \fBjx_parse_divert\fR() function offers a way to process each element
as it is parsed, without necessarily adding them to the parse tree.
.IP
You need to add the diversion to the parse state before you begin parsing
the data.
\fBjx_parse_divert\fR() takes three parameters:
\fIstate\fR is the parse state to add the diversion to,
\fIexpr\fR is a JavaScript-like expression for selecting the array within the
JSON data, and
\fIf\fR is a pointer to a function that will be called for each element of
the array.
.IP
The \fIf\fR function itself takes two parameters:
\fIstate\fR is the parse state, and
\fIelement\fR is the \fBjx_t\fR tree of the current element of the array.
The function should return the \fBjx_t\fR tree of the element to actually add,
or NULL if no element should be added to the array.
If the returned value isn't the \fIelement\fR parameter, then the function
should also call \fBjx_free\fR(\fIelement\fR) to free the element.
.IP
The \fBjx_parse_divert\fR() function returns a pointer to the structure
that it just added to the parse state.
You can store a pointer to your application's related data in the
.RI \" data \"
element before parsing begins,
and you can examine the
.RI \" diverted ",
.RI \"deleted \",
and
.RI \" changed \"
counters after parsing is complete.
Often, though, you can just discard the returned value.
.IP
The following example assumes "cust.json" contains an object with an array
of customer objects, e.g. {"cust":[{"custno":"1","name:"Bob Jones",...},...]}.
It processes the customers one by one, without adding any of them to the
parse tree.
The final parse tree will contain an empty "cust" array.
.nf
    #include <stdio.h>
    #include <jx.h>

    /* Process a single customer record */
    jx_t *docust(jx_parse_t *state, jx_t *element)
    {
        /* Print the custno and name fields */
        printf("%s\\t%s\\n",
            jx_text_by_key(element, "custno"),
            jx_text_by_key(element, "name"));

        /* Don't add this to the parse tree */
        jx_free(element);
        return NULL;
    }

    int main(int argc, char *argv)
    {
        int    i;
        jx_t *j;
        jx_parse_t state;

        jx_parse_begin(&state, 30);
        (void)jx_parse_divert(&state, "cust", docust);
        (void)jx_parse_file(&state, "cust.json");
        j = jx_parse_end(&state);
        jx_free(j);
        return 0;
    }
.fi

.IP "\fBchar\fR *jx_token(\fBchar\fR *\fIstr\fR, \fBjx_token_t\fR *\fItoken\fR);"
This is a low-level parsing function.
It parses a single token from a string, and returns a pointer to the next token.
The \fIstr\fR parameter is the start of the token to parse, and the
\fItoken\fR parameter is a pointer to a \fBjx_token_t\fR buffer that you
supply.
(Typically it would simply be declared as a local variable in a low-level
parsing function.)
.IP
Note that you probably will never have to use this function directly, because
the \fBjx_parse_string\fR() and \fBjx_parse_file\fR() deal with this for
you.

.IP "\fBint\fR jx_fix_empty_object;"
This is a boolean variable which affects the way JSON is parsed.
If true (non-zero), then any empty objects are converted into empty strings.
This is handy when dealing with JSON that was derived from an XML data source,
because XML is less expressive than JSON.
In JSON,
"foo":"" is clearly an empty string,
"foo":[] is clearly an empty array, and
"foo":{} is clearly an empty object, but in XML
<foo></foo> could be any empty thing.
Some libraries parse it as an empty object which is almost never correct.
In my experience, it should always be an empty string.
\fBjx_fix_empty_object\fR is false (0) by default so empty objects
continue to be parsed as empty objects.
Also, regardless of the value of \fRjx_fix_empty_object\fR, you can still
created and manipulate empty objects; this only affects parsing.
.IP "\fBvoid\fR jx_parse_token(\fBjx_parse_t\fR *\fIstate\fR, \fBjx_token_t\fR *\fItoken\fR);"
This is a low-level parsing function.
It incorporates a \fBjx_token_t\fR (e.g., from \fBjx_token\fR())
into a parse state.
You will probably never need to call this directly.
.IP
As an example,
here's the source code for the \fBjx_parse_string\fR() function:
.nf
    jx_t *jx_parse_string(char *str)
    {
            jx_parse_t state;
            jx_token_t token;

            /* Start parsing */
            jx_parse_begin(&state, 30);
            jx_parse_newbuf(&state, str, 0L);

            /* Parse each token and add it to data */
            while (*str)
            {
                    str = jx_token(str, &token);
                    jx_parse_token(&state, &token);
            }

            /* end parsing */
            return jx_parse_end(&state);
    }
.fi

.IP "\fBvoid\fR jx_parse_newbuf(\fBjx_parse_t\fR *\fIstate\fR, \fBchar\fR *\fIbuf\fR, long \fIoffset\fR);"
This is another low-level parsing function.
Its main purpose is to let the parser know where your parse buffer is located,
in the hope that this will allow better error messages to be given when the
JSON data contains errors.
The \fBjx_parse_file\fR() function does some complex buffer manipulation,
but usually you'd just pass the state, buffer, and 0L as the offset, for
each line of the data.

.SH "SERIALIZATING / OUTPUTTING"
The following functions convert a \fBjx_t\fR tree back into text.

.IP "\fBchar\fR *jx_serialize(\fBjx_t\fR *\fIjson\fR);"
This converts a \fBjx_t\fR tree into a compact string, following the
JSON conventions.
No newlines or spaces are added in an effort to make it pretty;
the serialized data is intended to be read by another computer program.
The returned string should be freed via the
.BR free (3)
standard library function after you're done with it.
.IP
The following example simply reads JSON data from "cust.json" and writes it
to stdout.
.nf
    #include <stdio.h>
    #include <jx.h>
    int main(int argc, char *argv)
    {
        jx_t *j;
        char   *str

        j = jx_parse_file(NULL, "cust.json");
        if (j) {
            str = jx_serialize(j);
            puts(str);
            free(str);
            jx_free(j);
        }
        return 0;
    }
.fi
.IP
Here's a more complex version which explicitly loops over the "cust" records
and serializes each element individually, instead of generating one big
string with all of them.
.nf
    #include <stdio.h>
    #include <jx.h>
    int main(int argc, char *argv)
    {
        jx_t *j, *cust, *elem;
        char   *str

        j = jx_parse_file(NULL, "cust.json");
        if (j) {
            printf("{\e"cust\e":[");
            cust = jx_by_key(j, "cust");
            for (elem = cust->first; elem; elem = elem->next) {
                str = jx_serialize(elem);
                puts(str);
                free(str);
                if (elem->next)
                    putchar(',');
            }
            printf("]}\en");
            jx_free(j);
        }
        return 0;
    }
.fi

.IP "\fBvoid\fR jx_print(\fBjx_t\fR *\fIjson\fR, FILE *\fIfp\fR, int \fIindent\fR);"
This writes JSON data to a \fIFILE\fR stream.
Unlike \fBjx_serialize\fR(), it does not convert it to a big string first
so it can be more efficient than \fBjx_serialize\fR().
Also, it can optionally "pretty-print" the JSON by adding newlines and spaces
to reveal the structure of the data.
.IP
The \fIjson\fR parameter is the data to output,
\fIfp\fR is the \fBFILE\fR stream to output it to, and
\fIindent\fR controls pretty-printing.
If \fIindent\fR is non-negative then the data will be pretty-printed, and the
\fIindent\fR value indicates how much indentation to add for the outermost
element, i.e. the "{" of the container object.
Passing -1 as the \fIindent\fR will inhibit pretty-printing, effectively
making it output the same text as \fBjx_serialize\fR().
Passing -2 as the \fIindent\fR adds newlines but no indentation, and also
inhibits some punctuation with the goal of making the text easier to parse
by a non-JSON-aware program.
.IP
This document already contains many pretty-printing examples, so here's one
that uses \fIindent\fR=-2 to output in the simplified multi-line format.
.nf
    #include <stdio.h>
    #include <jx.h>
    int main(int argc, char *argv)
    {
        jx_t *j;
        char   *str

        j = jx_parse_file(NULL, "cust.json");
        if (j) {
            jx_print(j, stdout, -2);
            jx_free(j);
        }
        return 0;
    }
.fi

.SH ACCESSING
The following functions allow you to locate and extract data from a
\fBjx_t\fR tree.

.IP "\fBjx_t\fR *jx_same(\fBjx_t\fR *\fIleft\fR, \fBjx_t\fR *\fIright\fR);"
Compare two \fBjx_t\fR trees and return 1 if they're the same, or 0 if
they're different.
This can be more complex than it sounds, because members of an object can be
listed in any order.
Also, if a member is present but its value is the symbol "null" then that's
equivalent to not being present.

.IP "\fBint\fR *jx_length(\fBjx_t\fR *\fIcontainer\fR);"
Return the number of elements in an array, or the number of members in an
object.
If passed NULL it will return 0.

.IP "\fBint\fR jx_is_null(\fBjx_t\fR *\fIjson\fR);"
Return 1 if
.I
json
is null, or 0 otherwise.
Note that "null" in this context may be either a NULL jx_t pointer,
or a JX_SYMBOL node with the value
.B null.

.IP "\fBint\fR jx_compare(\fBjx_t\fR *\fIobj1\fR, \fBjx_t\fR *\fIobj2\fR, \fBjx_t\fR *\fIorderby\fR);"
Compare two objects by looking at a listed set of fields.
Return 1 if
.I obj1
comes after
.IR obj2 ,
-1 if
.I obj1
comes before
.IR obj2 ,
or 0 if they compare as equal.
The
.I orderby
list is an array of strings giving member names or JavaScript-like expressesions
for finding values to compare.
Each name/expression may also be preceded by the symbol
.B true
to indicate that the values should be sorted in descending order instead of
the default ascending order.
For example, ["name", true, "age"] would compare records by ascending name,
but if names are equal then it will compare by descending age.
JX_NUMBER values are compared as numbers, and all else (strings and symbols,
mostly) are compared as case-insensitive strings.


.IP "\fBjx_t\fR *jx_by_key(\fBjx_t\fR *\fIcontainer\fR, \fBchar\fR *\fIkey\fR);"
.IP "\fBjx_t\fR *jx_by_deep_key(\fBjx_t\fR *\fIcontainer\fR, \fBchar\fR *\fIkey\fR);"
Locate a \fRjx_t\fR via its key.
The \fIcontainer\fR should be a \fBjx_t\fR tree of type \fBJX_OBJECT\fR
or \fBJX_ARRAY\fR.
The \fIcontainer\fR is scanned for a \fBJX_KEY\fR with the given name.
If found, the value (not the \fBJX_KEY\fR node itself) is returned.
If not found, NULL is returned.
.IP
.IP
The difference between \fBjx_by_key\fR() and \fBjx_by_deep_key\fR()
is that \fBjx_by_key\fR() only looks one layer deep in \fIcontainer\fR
while \fBjx_by_deep_key\fR() will look inside any objects within
\fIcontainer\fR for the requested key.

.IP "\fBjx_t\fR *jx_by_index(\fBjx_t\fR *\fIcontainer\fR, \fBint\fR \fIidx\fR);"
Locate a \fBjx_t\fR via its subscript.
The \fIcontainer\fR must be a \fIJX_ARRAY\fR.
The first element has \fIidx\fR=0.
keyed elements (as in an associative array) are not counted.
If the \fIidx\fR'th element doesn't exist, then NULL is returned instead.

.IP "\fBint\fR jx_ignorecase;"
This is a boolean variable.
If true (non-zero) then JavaScript-like expressions
as used by \fBjx_by_expr()\fR and \fBjx_parse_divert()\fR
will be case-insensitive.
\fBjx_ignorecase\fR is false (0) by default.
(You can also make any single expression be case-insensitive by adding a "~"
character to it.)

.IP "\fBjx_t\fR *jx_by_expr(\fBjx_t\fR *\fIcontainer\fR, \fBchar\fR *\fIexpr\fR, \fBchar\fR **\fInext\fR);"
Locate a \fBjx_t\fR via a JavaScript-like expression.
The \fIcontainer\fR should be a \fBJX_OBJECT\fR or \fBJX_ARRAY\fR,
\fIexpr\fR should be the expression in the form of a string, and
\fInext\fR, if not NULL, should be a reference to a character pointer that
will be set the end of the parsed expression.
The \fInext\fR parameter is intended to support
a comma-delimited list of expressions to look for.
.IP
The expression parser is pretty simple.
It divides each expression into a series of alphanumeric strings delimited by
any characters from the list ".[]".
You can also use quoted strings, as a way to access elements with names that
don't look like JavaScript identifiers.
Each string delves one layer deeper into the \fIcontainer\fR.
If the string looks like a number, then it uses \fBjx_find_by_index\fR(),
else it uses \fBjx_find_by_key\fR() except that if a double ".." appeared
in the delimiter then the \fBjx_find_by_deep_key()\fR function is used
instead.
Parsing stops when any other character (e.g., a space or comma) is encountered.
Here's a variation of the customer-processing function from the
\fBjx_parse_divert\fR() example.
Where the original example was hardcoded to output the custno and name fields,
this one use a global string to indicate what should be output.
This example is a code fragment, not a complete program.
.nf
    char *fields = "custno,name,address.zip,account[0].number";

    jx_t *docust(jx_parse_t *state, jx_t *element)
    {
	char *expr;
	jx_t *j;

        /* Print the requested fields */
        for (expr = fields; *expr; ) {
        	j = jx_by_expr(element, expr, &expr);
        	fputs(jx_text(j), stdout);
        	if (*expr) {
        		expr++; /* move past comma */
        		putchar('\et');
        	}
	}
	putchar('\en');

        /* Don't add this to the parse tree */
        jx_free(element);
        return NULL;
    }
.fi

.IP "\fBchar\fR *jx_text(\fBjx_t\fR *\fIjson\fR);"
Returns the text associated with a given \fBjx_t\fR node.
.IP
If passed NULL, it returns the default text.
The \fBJX_OBJECT\fR and \fBJX_ARRAY\fR types have no text and will return "".
For \fBJX_KEY\fR it returns the name of the keyed item;
use
.BI jx_text( json ->first)
to get the text of a keyed item.
For all others, it returns the value as a string; e.g. for if the \fBjx_t\fR's
\fItype\fR is JX_NUMBER and the value is 6, it'll return the string "6".
.IP
No effort is made to convert backslash sequences such as \en or \eu1234 to the
corresponding control characters or UTF-8 characters.

.IP "\fBchar\fR *jx_text_by_key(\fBjx_t\fR *\fIcontainer\fR, \fBchar\fR *\fIley\fR);"
.IP "\fBchar\fR *jx_text_by_index(\fBjx_t\fR *\fIcontainer\fR, \fBchar\fR *\fIindex\fR);"
.IP "\fBchar\fR *jx_text_by_expr(\fBjx_t\fR *\fIcontainer\fR, \fBchar\fR *\fIexpr\fR, \fBchar\fR **\fInext\fR);"
These are all convenience macros that combine \fBjx_text\fR() with one of the
\fBjx_by_\fIXXXXX\fR() functions.

.IP "\fBchar\fR *jx_default_text(\fBchar\fR *\fInewdefault\fR);"
This sets the default text returned by \fBjx_text\fR() when you pass
\fBjx_text\fR() a NULL \fBjx_t\fR value.
It returns the previous default.
Initially the default return value is a NULL character pointer,
though for some applications "" or the string "NULL" may be more useful.

.SH "SEE ALSO"
.BR jx (1)
.P
The JSON standard is defined in RFC-8259 (which replaced RFC-7159 in 2017)
and in ECMA-404.
.SH AUTHOR
Steve Kirkendall, kirkenda@gmail.com
